export const mockData = [
  {
    avatar: 'DF',
    className: '1. The Darts Factory',
    tutorName: 'Chan Tai Man',
    rating: 3.5,
    comment: '30',
    fee: '150',
    address: 'Address1',
    liked: true,
  },
  {
    avatar: 'AL',
    className: '2. The Darts Factory',
    tutorName: 'Wong Siu Ming',
    rating: 5,
    comment: '20',
    fee: '250',
    address: 'Address2',
    liked: false,
  },
  {
    avatar: 'SE',
    className: '3. The Darts Factory',
    tutorName: 'Wong Siu Ming',
    rating: 0,
    comment: '10',
    fee: '50',
    address: 'Address3',
    liked: false,
  },
]