// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:c73b8f4b-a98b-4d3c-8d74-d2ad5369a18d',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'tutorapp-hosting-mobilehub-741024213',
aws_content_delivery_bucket_region : 'ap-southeast-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'dr3k3hy5mvusv.cloudfront.net',
aws_dynamodb : 'enable',
aws_dynamodb_all_tables_region : 'ap-southeast-1',
aws_dynamodb_table_schemas : '[{"tableName":"tutorapp-mobilehub-741024213-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"userId","rangeKey":"petId"}]',
aws_mobile_analytics_app_id : '12cfa0ea027e46ad85ad502cf42e7dd6',
aws_project_id : '68db48c3-f076-43ee-9bc8-e7e552abba00',
aws_project_name : 'tutor-app',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'tutorapp-mobilehub-741024213',
aws_sign_in_enabled : 'enable',
aws_user_files : 'enable',
aws_user_files_s3_bucket : 'tutorapp-userfiles-mobilehub-741024213',
aws_user_files_s3_bucket_region : 'us-east-1',
aws_user_pools : 'enable',
aws_user_pools_id : 'us-east-1_fYJ30s5dT',
aws_user_pools_mfa_type : 'OFF',
aws_user_pools_web_client_id : '6sqqbq61ot314sdsqjsl2atvnj',
aws_user_settings : 'enable',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});

