//Application
export const SET_LANGUAGE = 'SET_LANGUAGE';

// Email Logins
export const SIGN_IN_EMAIL = 'SIGN_IN_EMAIL';
export const SIGN_IN_EMAIL_SUCCESS = 'SIGN_IN_EMAIL_SUCCESS';
export const SIGN_IN_EMAIL_FAIL = 'SIGN_IN_EMAIL_FAIL';

// Social Logins
export const SIGN_IN_FACEBOOK = 'SIGN_IN_FACEBOOK';
export const SIGN_IN_FACEBOOK_SUCCESS = 'SIGN_IN_FACEBOOK_SUCCESS';
export const SIGN_IN_FACEBOOK_FAIL = 'SIGN_IN_FACEBOOK_FAIL';

export const GET_FACEBOOK_PROFILE = 'GET_FACEBOOK_PROFILE';
export const GET_FACEBOOK_PROFILE_SUCCESS = 'GET_FACEBOOK_PROFILE_SUCCESS';
export const GET_FACEBOOK_PROFILE_FAIL = 'GET_FACEBOOK_PROFILE_FAIL';

export const GET_FACEBOOK_PICTURE = 'GET_FACEBOOK_PICTURE';
export const GET_FACEBOOK_PICTURE_SUCCESS = 'GET_FACEBOOK_PICTURE_SUCCESS';
export const GET_FACEBOOK_PICTURE_FAIL = 'GET_FACEBOOK_PICTURE_FAIL';

export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_IN_GOOGLE_SUCCESS = 'SIGN_IN_GOOGLE_SUCCESS';
export const SIGN_IN_GOOGLE_FAIL = 'SIGN_IN_GOOGLE_FAIL';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const VERIFY_CODE = 'VERIFY_CODE';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAIL = 'VERIFY_CODE_FAIL';
export const VERIFY_CODE_CANCEL = 'VERIFY_CODE_CANCEL';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_IDENTITY_ID = 'GET_IDENTITY_ID';
export const GET_IDENTITY_ID_SUCCESS = 'GET_IDENTITY_ID_SUCCESS';
export const GET_IDENTITY_ID_FAIL = 'GET_IDENTITY_ID_FAIL';

export const CREATE_CLASS = 'CREATE_CLASS';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const CREATE_CLASS_FAIL = 'CREATE_CLASS_FAIL';

export const GET_CLASS_LIST = 'GET_CLASS_LIST';
export const GET_CLASS_LIST_SUCCESS = 'GET_CLASS_LIST_SUCCESS';
export const GET_CLASS_LIST_FAIL = 'GET_CLASS_LIST_FAIL';

export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAIL = 'UPDATE_AVATAR_FAIL';
