//Application
export const SET_LANGUAGE = 'SET_LANGUAGE';

// Social Logins
export const SIGN_IN_FACEBOOK = 'SIGN_IN_FACEBOOK';
export const SIGN_IN_FACEBOOK_SUCCESS = 'SIGN_IN_FACEBOOK_SUCCESS';
export const SIGN_IN_FACEBOOK_FAIL = 'SIGN_IN_FACEBOOK_FAIL';

export const GET_FACEBOOK_PROFILE = 'GET_FACEBOOK_PROFILE';
export const GET_FACEBOOK_PROFILE_SUCCESS = 'GET_FACEBOOK_PROFILE_SUCCESS';
export const GET_FACEBOOK_PROFILE_FAIL = 'GET_FACEBOOK_PROFILE_FAIL';

export const GET_FACEBOOK_PICTURE = 'GET_FACEBOOK_PICTURE';
export const GET_FACEBOOK_PICTURE_SUCCESS = 'GET_FACEBOOK_PICTURE_SUCCESS';
export const GET_FACEBOOK_PICTURE_FAIL = 'GET_FACEBOOK_PICTURE_FAIL';

export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE';
export const SIGN_IN_GOOGLE_SUCCESS = 'SIGN_IN_GOOGLE_SUCCESS';
export const SIGN_IN_GOOGLE_FAIL = 'SIGN_IN_GOOGLE_FAIL';